List<Map<String,String>> acDrugs = [
  {
    "Generic": "Apixaban (High Dose)",
    "Dose": "\\>= 5 mg BID. If patient has 2 of the following, then >= 2.5 mg BID:\n* Age >= 80\n* Weight <= 60 kg\n* SCr >= 1.5 mg/dL",
    "Brand": "Eliquis",
    "Tags": "DOAC, Anti-Xa",
    "HoldPrior": "**ASRA**: 72 hours (or when residual apixaban plasma level < 30 ng/mL or residual aXa activity plasma level <=0.1 IU/mL)\n\n**ESAIC/ESRA**: 5 half-lives (~60 hours)",
    "ResumeAfter": "24 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place; 72 hours if unanticipated administration",
    "ResumeAfterCathRemoval": "24 hours",
    "Notes": ""
  },
  {
    "Generic": "Apixaban (Low Dose)",
    "Dose": "<= 2.5 mg BID",
    "Brand": "Eliquis",
    "Tags": "DOAC, Anti-Xa",
    "HoldPrior": "36 hours (or when residual apixaban plasma level < 30 ng/mL or residual aXa activity plasma level <=0.1 IU/mL)",
    "ResumeAfter": "6 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place; 36 hours if unanticipated administration",
    "ResumeAfterCathRemoval": "6 hours",
    "Notes": ""
  },
  {
    "Generic": "Edoxaban",
    "Dose": "",
    "Brand": "Savaysa",
    "Tags": "Lixiana, DOAC, Anti-Xa",
    "HoldPrior": "72 hours (or when residual edoxaban plasma level < 30 ng/mL or residual aXa activity)",
    "ResumeAfter": "24 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place; 72 hours if unanticipated administration",
    "ResumeAfterCathRemoval": "24 hours",
    "Notes": ""
  },
  {
    "Generic": "Rivaroxaban (High Dose)",
    "Dose": "* >= 20 mg daily(CrCl > 50 mL/min)\n* 15 mg daily (CrCl 15-50 mL/min)",
    "Brand": "Xarelto",
    "Tags": "DOAC, Anti-Xa",
    "HoldPrior": "72 hours (or when residual Xarelto plasma level < 30 ng/mL or residual aXa activity plasma level <=0.1 IU/mL)",
    "ResumeAfter": "24 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place; 72 hours if unanticipated administration",
    "ResumeAfterCathRemoval": "24 hours",
    "Notes": ""
  },
  {
    "Generic": "Rivaroxaban (Low Dose)",
    "Dose": "* <= 10 mg once per day (CrCl > 15 mL/min)",
    "Brand": "Xarelto",
    "Tags": "DOAC, Anti-Xa",
    "HoldPrior": "24 hours (or when residual Xarelto plasma level < 30 ng/mL or residual aXa activity plasma level <=0.1 IU/mL)",
    "ResumeAfter": "6 hours. ESAIC/ESRA: Consider prolonged time interval if bloody needle/catheter placement.",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place; 24 hours if unanticipated administration",
    "ResumeAfterCathRemoval": "6 hours",
    "Notes": ""
  },
  {
    "Generic": "Dabigatran (High Dose)",
    "Dose": "* >= 150 mg BID\n* 75 BID (CrCl 30-50 ml/min and concomitant use of P-glycoprotein inhibitors)\n* 75 mg BID (CrCl < 30 ml/min)",
    "Brand": "Pradaxa",
    "Tags": "Direct Thrombin Inhibitor, DOAC",
    "HoldPrior": "72 hours (CrCl >= 50 ml/min), 120 hours (CrCl 30-49 ml/min), or until plasma level is <30 ng/mL (CrCl < 30 ml/min)",
    "ResumeAfter": "24 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place; 72 hours (CrCl >= 50), 120 hours (CrCl 30-49) if unanticipated administration",
    "ResumeAfterCathRemoval": "",
    "Notes": ""
  },
  {
    "Generic": "Dabigatran (Low Dose)",
    "Dose": "<= 110 mg once per day first day followed by 220 mg daily (CrCl > 30 mL/min)",
    "Brand": "Pradaxa",
    "Tags": "Direct Thrombin Inhibitor, DOAC",
    "HoldPrior": "48 hours (CrCl > 30 ml/min), or when dabigatran plasma level is <30 ng/mL",
    "ResumeAfter": "6 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place; 48 hours if unanticipated administration of dabigatran",
    "ResumeAfterCathRemoval": "6 hours",
    "Notes": ""
  },
  {
    "Generic": "Heparin, IV Drip",
    "Dose": "",
    "Brand": "UFH",
    "Tags": "gtt, intravenous",
    "HoldPrior": "4-6 hours (assess coag studies prior to procedure)",
    "ResumeAfter": "1 hour",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place; if unanticipated heparizination, monitor neuro status",
    "ResumeAfterCathRemoval": "1 hour",
    "Notes": ""
  },
  {
    "Generic": "Heparin, Sub-Q (Low Dose)",
    "Dose": "5,000U BID-TID",
    "Brand": "SQH",
    "Tags": "subcutaneous, SQH, UFH",
    "HoldPrior": "4-6 hours after last SQH admin",
    "ResumeAfter": "Immediately",
    "HoldPriorCathRemoval": "At least 4-6 hours after last SQH admin",
    "ResumeAfterCathRemoval": "Immediately",
    "Notes": ""
  },
  {
    "Generic": "Heparin, Sub-Q (Med Dose)",
    "Dose": "7,500-10,000U BID",
    "Brand": "SQH",
    "Tags": "subcutaneous, SQH, UFH",
    "HoldPrior": "12 hours after last SQH admin",
    "ResumeAfter": "1 hour",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "1 hour",
    "Notes": ""
  },
  {
    "Generic": "Heparin, Sub-Q (High Dose)",
    "Dose": ">10,000U BID",
    "Brand": "SQH",
    "Tags": "subcutaneous, SQH, UFH",
    "HoldPrior": "24 hours after last SQH admin",
    "ResumeAfter": "1 hour",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "1 hour",
    "Notes": ""
  },
  {
    "Generic": "Enoxaparin (High Dose)",
    "Dose": "1 mg/kg every 12 hours or 1.5 mg/kg once daily",
    "Brand": "Lovenox",
    "Tags": "low molecular weight heparin, LMWH",
    "HoldPrior": "**ASRA**: 24 hours after last admin.\n\n**ESAIC/ESRA**: Hold 2-3 half-lives (~36 hours) after last administration",
    "ResumeAfter": "24 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "4 hours",
    "Notes": ""
  },
  {
    "Generic": "Enoxaparin (Low Dose BID)",
    "Dose": "30 mg BID",
    "Brand": "Lovenox",
    "Tags": "low molecular weight heparin, LMWH",
    "HoldPrior": "12 hours after last admin",
    "ResumeAfter": "Following day and at least 12 hours after needle/catheter placement",
    "HoldPriorCathRemoval": "At least 12 hours after last admin",
    "ResumeAfterCathRemoval": "4 hours",
    "Notes": ""
  },
  {
    "Generic": "Enoxaparin (Low Dose Daily)",
    "Dose": "40 mg daily",
    "Brand": "Lovenox",
    "Tags": "low molecular weight heparin, LMWH",
    "HoldPrior": "12 hours after last admin",
    "ResumeAfter": "First dose at least 12 hours after needle placement. Second dose 24 hours after first.",
    "HoldPriorCathRemoval": "At least 12 hours after last admin",
    "ResumeAfterCathRemoval": "4 hours",
    "Notes": ""
  },
  {
    "Generic": "NSAIDs",
    "Dose": "",
    "Brand": "Advil, Motrin, Mobic, Aleve",
    "Tags": "Ibuprofen, meloxicam, naproxen",
    "HoldPrior": "No need to hold",
    "ResumeAfter": "No need to hold",
    "HoldPriorCathRemoval": "No need to hold",
    "ResumeAfterCathRemoval": "No need to hold",
    "Notes": "While NSAIDs alone do not significantly increase bleeding risk, patients receiving multiple anticoagulants simultaneously carry an increased risk of bleeding complications."
  },
  {
    "Generic": "Clopidogrel",
    "Dose": "",
    "Brand": "Plavix",
    "Tags": "P2Y12 platelet inhibitor, thienopyridine, antiplatelet",
    "HoldPrior": "5-7 days",
    "ResumeAfter": "6 hours (if giving loading dose). Otherwise, can resume maintenance immediately",
    "HoldPriorCathRemoval": "If resuming maintenance therapy after catheter placement, remove the catheter within 1-2 days. Do NOT administer loading dose.",
    "ResumeAfterCathRemoval": "6 hours (if giving loading dose). Otherwise, can resume maintenance immediately",
    "Notes": ""
  },
  {
    "Generic": "Prasugrel",
    "Dose": "",
    "Brand": "Effient",
    "Tags": "P2Y12 platelet inhibitor, thienopyridine, antiplatelet",
    "HoldPrior": "7-10 days",
    "ResumeAfter": "6 hours (if giving loading dose). Otherwise, can resume maintenance immediately",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "6 hours (if giving loading dose). Otherwise, can resume maintenance immediately",
    "Notes": ""
  },
  {
    "Generic": "Ticagrelor",
    "Dose": "",
    "Brand": "Brilinta",
    "Tags": "P2Y12 platelet inhibitor, antiplatelet",
    "HoldPrior": "5 days",
    "ResumeAfter": "6 hours (if giving loading dose). Otherwise, can resume maintenance immediately",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "6 hours (if giving loading dose). Otherwise, can resume maintenance immediately",
    "Notes": ""
  },
  {
    "Generic": "Abciximab",
    "Dose": "",
    "Brand": "ReoPro",
    "Tags": "Platelet inhibitor, antiplatelet, GP IIb/IIIa",
    "HoldPrior": "24-48 hours",
    "ResumeAfter": "4 Weeks (if abciximab has to be given emergently, consider opioids only in neuraxial infusion to maximize neurological monitoring)",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "4 Weeks (if abciximab has to be given emergently, consider opioids only in neuraxial infusion to maximize neurological monitoring)",
    "Notes": ""
  },
  {
    "Generic": "Eptifibatide",
    "Dose": "",
    "Brand": "Integrilin",
    "Tags": "Platelet inhibitor, antiplatelet, GP IIb/IIIa",
    "HoldPrior": "4-8 hours",
    "ResumeAfter": "4 Weeks (if eptifibatide has to be given emergently, consider opioids only in neuraxial infusion to maximize neurological monitoring)",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "4 Weeks (if eptifibatide has to be given emergently, consider opioids only in neuraxial infusion to maximize neurological monitoring)",
    "Notes": ""
  },
  {
    "Generic": "Tirofiban",
    "Dose": "",
    "Brand": "Aggrastat",
    "Tags": "Platelet inhibitor, antiplatelet, GP IIb/IIIa",
    "HoldPrior": "4-8 hours",
    "ResumeAfter": "4 Weeks (if tirofiban has to be given emergently, consider opioids only in neuraxial infusion to maximize neurological monitoring)",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "4 Weeks (if tirofiban has to be given emergently, consider opioids only in neuraxial infusion to maximize neurological monitoring)",
    "Notes": ""
  },
  {
    "Generic": "Cilostazol",
    "Dose": "",
    "Brand": "Pletal",
    "Tags": "PDE-3 inhibitor, phosphodiesterase III",
    "HoldPrior": "2 days",
    "ResumeAfter": "6 hours (if giving loading dose). Otherwise, can resume maintenance immediately",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "8 hours",
    "Notes": ""
  },
  {
    "Generic": "Cangrelor",
    "Dose": "",
    "Brand": "Kengreal",
    "Tags": "P2Y12 platelet inhibitor antiplatelet",
    "HoldPrior": "3 hours",
    "ResumeAfter": "8 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "8 hours",
    "Notes": ""
  },
  {
    "Generic": "Fondaparinux (Low Dose)",
    "Dose": "2.5 mg daily",
    "Brand": "Arixtra",
    "Tags": "Anti-Xa",
    "HoldPrior": "* 36 hours (young and normal renal function)\n\n* 42 hours (elderly and normal renal function)\n\n* 58 hours (CrCl 30-50 ml/min)\n\n* Do not do procedure for CrCl < 30 ml/min",
    "ResumeAfter": "6 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "6 hours",
    "Notes": ""
  },
  {
    "Generic": "Fondaparinux (High Dose)",
    "Dose": "5-10 mg daily",
    "Brand": "Arixtra",
    "Tags": "Anti-Xa",
    "HoldPrior": "* 70 hours (young and normal renal function)\n* 105 hours (elderly and normal renal function)\n* If placing needle prior to suggested times then ensure anti Xa level < 0.1 \n* Consider not doing procedure if renal function impaired",
    "ResumeAfter": "6 hours",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "6 hours",
    "Notes": ""
  },
  {
    "Generic": "Thrombolytic",
    "Dose": "",
    "Brand": "tPA, TNK, etc.",
    "Tags": "clot buster",
    "HoldPrior": "48 hours (consider checking coags before procedure)",
    "ResumeAfter": "tPA relatively contraindicated within 10 days of procedure. (if tPa has to be given emergently, consider opioids only in neuraxial infusion to maximize neurological monitoring)",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "tPA relatively contraindicated within 10 days of procedure. Continue neurological exam for 48 hours following catheter removal.",
    "Notes": ""
  },
  {
    "Generic": "Herbal Therapy",
    "Dose": "",
    "Brand": "Garlic, Ginkgo, Ginseng, etc.",
    "Tags": "voodoo",
    "HoldPrior": "No need to hold",
    "ResumeAfter": "No need to hold",
    "HoldPriorCathRemoval": "No need to hold",
    "ResumeAfterCathRemoval": "No need to hold",
    "Notes": ""
  },
  {
    "Generic": "Warfarin",
    "Dose": "",
    "Brand": "Coumadin",
    "Tags": "INR",
    "HoldPrior": "5 days (recheck INR prior to procedure)",
    "ResumeAfter": "Can restart Warfarin immediately. Continue neuro assessment for 48 hours after restarting Warfarin",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place; remove when INR < 1.5",
    "ResumeAfterCathRemoval": "Can restart warfarin immediately. Continue neurologcal monitoring for 48 hours after restarting warfarin.",
    "Notes": ""
  },
  {
    "Generic": "Dalteparin (High Dose)",
    "Dose": "120 IU/kg every 12 hours or 200 IU/kg once daily",
    "Brand": "Fragmin",
    "Tags": "low molecular weight heparin, LMWH",
    "HoldPrior": "24 hours after last administration",
    "ResumeAfter": "24 hours (after low bleeding risk surgery); 48-72 hours (after high bleeding risk surgery)",
    "HoldPriorCathRemoval": "Not advised per ASRA while catheter in place",
    "ResumeAfterCathRemoval": "4 hours",
    "Notes": ""
  },
  {
    "Generic": "Dalteparin (Low Dose)",
    "Dose": "5000 IU once daily",
    "Brand": "Fragmin",
    "Tags": "low molecular weight heparin, LMWH",
    "HoldPrior": "12 hours after last administration",
    "ResumeAfter": "First dose at least 12 hours after needle placement. Second dose 24 hours after first.",
    "HoldPriorCathRemoval": "At least 12 hours",
    "ResumeAfterCathRemoval": "4 hours",
    "Notes": ""
  }
];